version: '3'
services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - ./:/var/www
    depends_on:
      - db-app-task-list
      - dependency-manager-composer
    networks:
      - app-task-list-network

  app-nginx:
    container_name: app-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-task-list-network

  db-app-task-list:
    container_name: db-app-task-list
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: techchallenge
      MYSQL_DATABASE: buzzvel-tech-challange
    networks:
      - app-task-list-network

  dependency-manager-composer:
    container_name: dependency-manager-composer
    build:
        context: .
        dockerfile: ./DockerFile-dependency-manager-composer
    command: composer install
    volumes:
        - ./:/var/www/

networks:
  app-task-list-network:
    driver: bridge